import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type LegalKind = "terms" | "privacy" | "support";

const copy = {
  ar: {
    terms: { kicker: "قواعد المنصة", title: "شروط استخدام سوقنا سوريا", lead: "هذه مسودة تشغيلية توضح السلوك المطلوب عند استخدام المنصة. يجب مراجعتها واعتمادها قانونيًا من مالك المشروع قبل إرسال التطبيق إلى المتاجر.", sections: [["الاستخدام المسؤول", "يجب أن تكون الإعلانات والرسائل صحيحة ومشروعة ومحترمة، وألا تتضمن احتيالًا أو انتحالًا أو محتوى مسيئًا أو مخالفًا للقانون."], ["المحتوى والإدارة", "يجوز للمنصة مراجعة البلاغات، وإيقاف المحتوى أو الحسابات المخالفة، والتعاون مع الجهات المختصة عند الاقتضاء."], ["سلامة التعامل", "لا ترسل أموالًا أو وثائق حساسة قبل التحقق المباشر من الطرف والإعلان. المنصة لا تكون طرفًا في البيع أو الاتفاق بين المستخدمين."]], support: "الدعم وطلب حذف البيانات" },
    privacy: { kicker: "خصوصيتك", title: "سياسة خصوصية سوقنا سوريا", lead: "تشرح هذه المسودة طريقة التعامل مع البيانات في النسخة الحالية. يجب أن تعتمدها الجهة المالكة وتحدّثها إذا تغيرت الخدمات أو طرق الدفع أو التسجيل.", sections: [["البيانات التي قد تُعالج", "قد تشمل بيانات الحساب في الموقع، وبيانات الإعلان، والصور التي يختار المستخدم رفعها، والموقع التقريبي عند منح الإذن، والرسائل والبلاغات وطلبات الدعم."], ["سبب المعالجة", "نستخدم البيانات لتشغيل الإعلانات والدردشة، ومنع إساءة الاستخدام، والرد على طلبات الدعم، والوفاء بالالتزامات القانونية ذات الصلة."], ["الحفظ والحماية", "تُحفظ البيانات فقط بالقدر اللازم لتشغيل الخدمة ومعالجة البلاغات والالتزامات. يمكن للمستخدم المسجل تقديم طلب حذف، ويخضع الطلب لمراجعة تحمي حقوق المستخدمين الآخرين والالتزامات القانونية."], ["المشاركة", "لا نبيع بياناتك. قد نستخدم مزودي تخزين أو استضافة لتشغيل الخدمة ضمن الحدود اللازمة، وقد نفصح عن المعلومات عند وجود التزام قانوني."], ["التحديثات", "سننشر أي تغيير جوهري في هذه الصفحة ونطلب قبول إصدار محدث من السياسات قبل نشر محتوى جديد عند الحاجة."]], support: "الدعم وطلب حذف البيانات" },
    support: { kicker: "نحن هنا للمساعدة", title: "الدعم وطلبات البيانات", lead: "أرسل تذكرة للدعم للبلاغات العامة أو الأسئلة أو مشاكل الحساب. لا ترسل كلمات مرور أو أرقام بطاقات أو وثائق شخصية في الرسالة.", sections: [], support: "إرسال تذكرة دعم" },
    labels: { name: "الاسم", email: "البريد الإلكتروني", subject: "الموضوع", message: "الرسالة", submit: "إرسال التذكرة", sent: "تم استلام تذكرتك وسنراجعها.", deletion: "طلب حذف بياناتي", deletionHelp: "إن كنت مسجلًا، يمكنك طلب حذف بيانات الحساب من هنا. لا يؤدي الطلب إلى حذف فوري قبل المراجعة.", deletionSent: "تم تسجيل طلب حذف البيانات للمراجعة.", links: "راجع أيضًا" },
  },
  en: {
    terms: { kicker: "Platform rules", title: "Souqna Syria Terms of Use", lead: "This operational draft explains the required conduct on the platform. It must be legally reviewed and approved by the project owner before app-store submission.", sections: [["Responsible use", "Listings and messages must be accurate, lawful, and respectful. They must not include fraud, impersonation, abusive material, or illegal content."], ["Content and moderation", "The platform may review reports, restrict violating content or accounts, and cooperate with relevant authorities where appropriate."], ["Transaction safety", "Do not send money or sensitive documents before directly verifying the other party and the listing. The platform is not a party to a sale or agreement between users."]], support: "Support and data deletion" },
    privacy: { kicker: "Your privacy", title: "Souqna Syria Privacy Policy", lead: "This draft describes data handling in the current release. The owner must approve and update it if services, payments, or sign-in methods change.", sections: [["Data we may process", "This can include website account data, listing data, images a user chooses to upload, approximate location when permission is granted, messages, reports, and support requests."], ["Why we process it", "We use data to operate listings and messaging, prevent abuse, answer support requests, and meet applicable legal obligations."], ["Retention and security", "Data is retained only as needed to operate the service, handle reports, and meet obligations. Signed-in users can request deletion; requests are reviewed to protect other users' rights and legal duties."], ["Sharing", "We do not sell personal data. We may use hosting or storage providers to operate the service and disclose information when legally required."], ["Updates", "Material changes will be published here, and an updated policy version can be required before new content is posted."]], support: "Support and data deletion" },
    support: { kicker: "We can help", title: "Support and data requests", lead: "Send a support ticket for general questions or account issues. Do not send passwords, card numbers, or identity documents in your message.", sections: [], support: "Send support ticket" },
    labels: { name: "Name", email: "Email", subject: "Subject", message: "Message", submit: "Send ticket", sent: "Your ticket was received and will be reviewed.", deletion: "Request deletion of my data", deletionHelp: "If you are signed in, you can request account-data deletion here. A request is not an immediate deletion before review.", deletionSent: "Your data-deletion request was recorded for review.", links: "See also" },
  },
  tr: {
    terms: { kicker: "Platform kuralları", title: "Souqna Suriye Kullanım Koşulları", lead: "Bu operasyon taslağı, platformdaki gerekli davranışları açıklar. Uygulama mağazalarına sunulmadan önce proje sahibi tarafından hukuki olarak gözden geçirilip onaylanmalıdır.", sections: [["Sorumlu kullanım", "İlanlar ve mesajlar doğru, yasal ve saygılı olmalıdır; dolandırıcılık, kimliğe bürünme, zararlı veya yasa dışı içerik içeremez."], ["İçerik ve denetim", "Platform, bildirimleri inceleyebilir, ihlal eden içerik veya hesapları kısıtlayabilir ve gerektiğinde ilgili makamlarla iş birliği yapabilir."], ["İşlem güvenliği", "Karşı tarafı ve ilanı doğrudan doğrulamadan para veya hassas belge göndermeyin. Platform, kullanıcılar arasındaki satışın veya anlaşmanın tarafı değildir."]], support: "Destek ve veri silme" },
    privacy: { kicker: "Gizliliğiniz", title: "Souqna Suriye Gizlilik Politikası", lead: "Bu taslak, mevcut sürümdeki veri işleme biçimini açıklar. Hizmetler, ödemeler veya giriş yöntemleri değişirse sahibi tarafından onaylanmalı ve güncellenmelidir.", sections: [["İşleyebileceğimiz veriler", "Web sitesi hesap verileri, ilan verileri, kullanıcının yüklemeyi seçtiği görseller, izin verildiğinde yaklaşık konum, mesajlar, bildirimler ve destek talepleri buna dahil olabilir."], ["İşleme amacı", "Verileri ilanları ve mesajlaşmayı çalıştırmak, kötüye kullanımı önlemek, destek taleplerini yanıtlamak ve yasal yükümlülükleri karşılamak için kullanırız."], ["Saklama ve güvenlik", "Veriler yalnızca hizmeti işletmek, bildirimleri işlemek ve yükümlülükleri karşılamak için gerekli süreyle saklanır. Giriş yapan kullanıcılar silme talebinde bulunabilir; talepler diğer kullanıcı haklarını ve yasal görevleri korumak için incelenir."], ["Paylaşım", "Kişisel verileri satmayız. Hizmeti çalıştırmak için barındırma veya depolama sağlayıcıları kullanabilir ve yasal olarak gerektiğinde bilgi açıklayabiliriz."], ["Güncellemeler", "Önemli değişiklikler burada yayımlanır ve yeni içerik gönderilmeden önce güncel politika sürümünün kabulü istenebilir."]], support: "Destek ve veri silme" },
    support: { kicker: "Yardım için buradayız", title: "Destek ve veri talepleri", lead: "Genel sorular veya hesap sorunları için destek talebi gönderin. Mesajınıza parola, kart numarası veya kimlik belgesi eklemeyin.", sections: [], support: "Destek talebi gönder" },
    labels: { name: "Ad", email: "E-posta", subject: "Konu", message: "Mesaj", submit: "Talep gönder", sent: "Talebiniz alındı ve incelenecek.", deletion: "Verilerimin silinmesini iste", deletionHelp: "Giriş yaptıysanız hesap verilerinizin silinmesini buradan isteyebilirsiniz. Talep, inceleme öncesinde anında silme anlamına gelmez.", deletionSent: "Veri silme talebiniz inceleme için kaydedildi.", links: "Ayrıca bakın" },
  },
} as const;

export default function Legal({ kind }: { kind: LegalKind }) {
  const { locale, dir } = useLanguage();
  const { user } = useAuth();
  const language = copy[locale];
  const page = language[kind];
  const [form, setForm] = useState({ name: user?.name || "", email: user?.email || "", subject: "", message: "" });
  const submitTicket = trpc.support.create.useMutation({ onSuccess: () => { toast.success(language.labels.sent); setForm(current => ({ ...current, subject: "", message: "" })); }, onError: error => toast.error(error.message) });
  const requestDeletion = trpc.safety.requestDataDeletion.useMutation({ onSuccess: () => toast.success(language.labels.deletionSent), onError: error => toast.error(error.message) });

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    submitTicket.mutate(form);
  }

  return <main className="page-shell bg-[#fcfaf6] py-10" dir={dir}><div className="container max-w-3xl"><p className="section-kicker">{page.kicker}</p><h1 className="section-title">{page.title}</h1><p className="mt-3 text-sm leading-7 text-[#69746f]">{page.lead}</p>{kind !== "support" && <div className="mt-8 space-y-4">{page.sections.map(([heading, body]) => <section key={heading} className="rounded-2xl border border-[#e9e3da] bg-white p-5"><h2 className="font-extrabold text-[#2d4a44]">{heading}</h2><p className="mt-2 text-sm leading-7 text-[#66736e]">{body}</p></section>)}</div>}{kind === "support" && <><form onSubmit={submit} className="mt-8 space-y-4 rounded-2xl border border-[#e9e3da] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="form-field">{language.labels.name}<input required value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} /></label><label className="form-field">{language.labels.email}<input required type="email" value={form.email} onChange={event => setForm(current => ({ ...current, email: event.target.value }))} /></label></div><label className="form-field">{language.labels.subject}<input required value={form.subject} onChange={event => setForm(current => ({ ...current, subject: event.target.value }))} /></label><label className="form-field">{language.labels.message}<textarea required minLength={10} rows={6} value={form.message} onChange={event => setForm(current => ({ ...current, message: event.target.value }))} /></label><Button type="submit" disabled={submitTicket.isPending}>{language.labels.submit}</Button></form><section className="mt-5 rounded-2xl border border-[#e9e3da] bg-[#edf4ef] p-5"><h2 className="font-extrabold text-[#2d4a44]">{language.labels.deletion}</h2><p className="mt-2 text-sm leading-7 text-[#66736e]">{language.labels.deletionHelp}</p>{user && <Button className="mt-4" type="button" variant="outline" disabled={requestDeletion.isPending} onClick={() => requestDeletion.mutate({})}>{language.labels.deletion}</Button>}</section></>}{kind !== "support" && <p className="mt-7 text-xs text-[#71807a]">{language.labels.links}: <Link className="font-bold text-[#1a6257]" href="/terms">{copy[locale].terms.title}</Link> · <Link className="font-bold text-[#1a6257]" href="/privacy">{copy[locale].privacy.title}</Link> · <Link className="font-bold text-[#1a6257]" href="/support">{copy[locale].support.support}</Link></p>}</div></main>;
}
