import AsyncStorage from "@react-native-async-storage/async-storage";

export type MobileLocale = "ar" | "en" | "tr";
type TranslationValues = Record<string, string | number>;

const words: Record<MobileLocale, Record<string, string>> = {
  ar: {
    home: "الرئيسية", search: "البحث", publish: "أضف", mine: "إعلاناتي", account: "حسابي", hero: "إعلانك المناسب أقرب إليك", subtitle: "تصفح العقارات والسيارات والوظائف والخدمات بسهولة.", searchHint: "ماذا تبحث عنه اليوم؟", browseCategory: "تصفح حسب القسم", latest: "أحدث الإعلانات", searchTitle: "ابحث في الإعلانات", searchExample: "مثال: شقة في دمشق أو كيا", category: "القسم", province: "المحافظة", price: "السعر", searchNow: "ابحث الآن", noResults: "لا توجد إعلانات مطابقة", detail: "الوصف", back: "العودة إلى النتائج", contact: "التواصل مع المعلن", language: "اللغة", messages: "الرسائل", login: "تسجيل الدخول", realEstate: "العقارات", vehicles: "السيارات", jobs: "الوظائف", used: "المستعمل", services: "الخدمات",
    publishTitle: "أضف إعلانًا", publishHelper: "ابدأ بتحديد القسم ثم أضف بيانات الإعلان. النشر مجاني حاليًا.", listingTitle: "عنوان الإعلان", listingTitleExample: "مثال: شقة غرفتين للإيجار", provinceExample: "مثال: دمشق", publishHintRealEstate: "أضف نوع العقار والمساحة وعدد الغرف بعد تسجيل الدخول.", publishHintVehicles: "أضف الماركة والطراز وسنة الصنع بعد تسجيل الدخول.", publishHintDefault: "أكمل الحقول المناسبة للقسم بعد تسجيل الدخول.", addImages: "إضافة صور", imagesSelected: "{count} صور مختارة", chooseLocation: "تحديد الموقع", saveDraft: "حفظ المسودة", openPublish: "تسجيل الدخول والنشر في المنصة", opening: "جارٍ الفتح…", enterDetails: "أدخل عنوانًا واضحًا ومحافظة الإعلان أولًا.", draftSaved: "تم حفظ المسودة، بما فيها الصور المختارة والموقع، على هذا الجهاز. أكمل الإرسال بعد تسجيل الدخول في المنصة.", draftRestored: "تمت استعادة مسودتك المحفوظة على هذا الجهاز.", draftOpenNotice: "ستبقى مسودتك محفوظة في التطبيق. بعد تسجيل الدخول، أكمل الحقول وارفع الصور في صفحة النشر الآمنة.", browserCancelledDraft: "أُغلق المتصفح قبل إكمال النشر. ستبقى مسودتك محفوظة ويمكنك المحاولة مجددًا.", browserOpenedPublish: "فُتحت صفحة النشر الآمنة. أكمل تسجيل الدخول ثم أدخل بيانات الإعلان وارفع الصور هناك.", browserFailedPublish: "تعذر فتح صفحة النشر. تحقق من اتصال الإنترنت ثم حاول مجددًا؛ مسودتك ما زالت محفوظة.", imagePermission: "يجب السماح بالوصول إلى الصور لإرفاقها بالإعلان.", imagesPicked: "تم اختيار {count} صورة. احفظ المسودة للاحتفاظ بها على الجهاز.", locationPermission: "لم تمنح إذن الموقع؛ يمكنك إكمال الإعلان دون تحديد الموقع الآن.", locationSaved: "تم تحديد الموقع التقريبي: {latitude}، {longitude}. احفظ المسودة للاحتفاظ به.", locationRestored: "تمت استعادة الموقع: {latitude}، {longitude}.",
    myListingsTitle: "إعلاناتي", manageTitle: "إدارة إعلاناتك من مكان واحد", manageDetail: "بعد تسجيل الدخول ستظهر إعلاناتك مع خيارات التعديل أو الإيقاف أو الحذف.", myListingsStatus: "حالة إعلاناتي", myListingsStatusDetail: "تحتاج هذه البيانات إلى تسجيل دخول. تُفتح الصفحة في متصفح آمن كي لا تُخزَّن جلسة الحساب داخل التطبيق خلال مرحلة الربط الحالية.", openMyListings: "فتح إعلاناتي", openingMyListings: "جارٍ فتح صفحة إعلاناتك الآمنة…", browserCancelled: "أُغلق المتصفح قبل إكمال العملية. يمكنك المحاولة مجددًا.", browserOpenedMyListings: "فُتحت صفحة إعلاناتك في المتصفح الآمن. بعد تسجيل الدخول ستظهر خيارات الإدارة.", browserFailedMyListings: "تعذر فتح صفحة إعلاناتي. تحقق من اتصال الإنترنت ثم حاول مجددًا.", accountTitle: "حسابي", signInTitle: "سجّل الدخول للمتابعة", signInDetail: "استخدم حسابك للوصول إلى إعلاناتك والتنبيهات وبيانات التواصل.", openMessages: "فتح الرسائل وتسجيل الدخول", openNotifications: "فتح التنبيهات", openingMessages: "جارٍ فتح الرسائل…", openingNotifications: "جارٍ فتح التنبيهات…", browserOpenedProtected: "فُتحت {label} في المتصفح الآمن. سجّل الدخول للوصول إلى بيانات حسابك.", browserFailedProtected: "تعذر فتح {label}. تحقق من اتصال الإنترنت ثم حاول مجددًا.", chatTitle: "الدردشة مع المعلن", chatDetail: "من صفحة الإعلان أو الرسائل، يمكنك فتح محادثة خاصة وآمنة مع مالك الإعلان.", notificationsTitle: "التنبيهات", notificationsDetail: "ستظهر هنا تحديثات حالة الإعلان واهتمامات المتصفحين بعد تسجيل الدخول.",
  },
  en: {
    home: "Home", search: "Search", publish: "Post", mine: "My ads", account: "Account", hero: "The right listing is closer", subtitle: "Explore real estate, vehicles, jobs, and services with ease.", searchHint: "What are you looking for?", browseCategory: "Browse by category", latest: "Latest listings", searchTitle: "Search listings", searchExample: "Example: apartment in Damascus or Kia", category: "Category", province: "Province", price: "Price", searchNow: "Search now", noResults: "No matching listings", detail: "Description", back: "Back to results", contact: "Contact advertiser", language: "Language", messages: "Messages", login: "Sign in", realEstate: "Real estate", vehicles: "Vehicles", jobs: "Jobs", used: "Used goods", services: "Services",
    publishTitle: "Post a listing", publishHelper: "Choose a category, then add the listing details. Posting is currently free.", listingTitle: "Listing title", listingTitleExample: "Example: two-bedroom apartment for rent", provinceExample: "Example: Damascus", publishHintRealEstate: "Add the property type, area, and room count after you sign in.", publishHintVehicles: "Add make, model, and year after you sign in.", publishHintDefault: "Complete the fields that fit this category after you sign in.", addImages: "Add photos", imagesSelected: "{count} photos selected", chooseLocation: "Choose location", saveDraft: "Save draft", openPublish: "Sign in and post on the platform", opening: "Opening…", enterDetails: "Enter a clear title and province first.", draftSaved: "Your draft, including selected photos and location, was saved on this device. Sign in on the platform to complete posting.", draftRestored: "Your saved draft was restored on this device.", draftOpenNotice: "Your draft remains saved in the app. After signing in, complete the fields and upload photos on the secure posting page.", browserCancelledDraft: "The browser closed before posting was completed. Your draft remains saved; you can try again.", browserOpenedPublish: "The secure posting page is open. Sign in, then enter the listing details and upload its photos there.", browserFailedPublish: "The posting page could not be opened. Check your connection and try again; your draft is still saved.", imagePermission: "Allow photo access to attach images to the listing.", imagesPicked: "{count} photos selected. Save the draft to keep them on this device.", locationPermission: "Location access was not granted; you can continue without setting a location now.", locationSaved: "Approximate location selected: {latitude}, {longitude}. Save the draft to keep it.", locationRestored: "Location restored: {latitude}, {longitude}.",
    myListingsTitle: "My listings", manageTitle: "Manage your listings in one place", manageDetail: "After you sign in, your listings will appear with options to edit, pause, or delete.", myListingsStatus: "My listings status", myListingsStatusDetail: "These data require sign-in. The page opens in a secure browser so the account session is not stored in the app during this integration stage.", openMyListings: "Open my listings", openingMyListings: "Opening your secure listings page…", browserCancelled: "The browser closed before the action was completed. You can try again.", browserOpenedMyListings: "Your listings page opened in a secure browser. Sign in to manage your listings.", browserFailedMyListings: "Your listings page could not be opened. Check your connection and try again.", accountTitle: "Account", signInTitle: "Sign in to continue", signInDetail: "Use your account to access listings, notifications, and contact details.", openMessages: "Open messages and sign in", openNotifications: "Open notifications", openingMessages: "Opening messages…", openingNotifications: "Opening notifications…", browserOpenedProtected: "{label} opened in a secure browser. Sign in to access your account data.", browserFailedProtected: "{label} could not be opened. Check your connection and try again.", chatTitle: "Chat with the advertiser", chatDetail: "From the listing page or messages, you can start a private, secure conversation with the listing owner.", notificationsTitle: "Notifications", notificationsDetail: "Listing-status updates and user interests will appear here after you sign in.",
  },
  tr: {
    home: "Ana sayfa", search: "Ara", publish: "İlan ver", mine: "İlanlarım", account: "Hesabım", hero: "Doğru ilan size daha yakın", subtitle: "Emlak, araç, iş ve hizmetleri kolayca keşfedin.", searchHint: "Ne arıyorsunuz?", browseCategory: "Kategoriye göre keşfedin", latest: "En yeni ilanlar", searchTitle: "İlanlarda ara", searchExample: "Örnek: Şam'da daire veya Kia", category: "Kategori", province: "İl", price: "Fiyat", searchNow: "Ara", noResults: "Eşleşen ilan yok", detail: "Açıklama", back: "Sonuçlara dön", contact: "İlan sahibiyle iletişim", language: "Dil", messages: "Mesajlar", login: "Giriş yap", realEstate: "Emlak", vehicles: "Araçlar", jobs: "İşler", used: "İkinci el", services: "Hizmetler",
    publishTitle: "İlan ver", publishHelper: "Önce kategoriyi seçin, sonra ilan bilgilerini ekleyin. İlan verme şu anda ücretsizdir.", listingTitle: "İlan başlığı", listingTitleExample: "Örnek: kiralık iki odalı daire", provinceExample: "Örnek: Şam", publishHintRealEstate: "Giriş yaptıktan sonra taşınmaz türünü, alanını ve oda sayısını ekleyin.", publishHintVehicles: "Giriş yaptıktan sonra marka, model ve üretim yılını ekleyin.", publishHintDefault: "Giriş yaptıktan sonra bu kategoriye uygun alanları tamamlayın.", addImages: "Fotoğraf ekle", imagesSelected: "{count} fotoğraf seçildi", chooseLocation: "Konum seç", saveDraft: "Taslağı kaydet", openPublish: "Giriş yap ve platformda ilan ver", opening: "Açılıyor…", enterDetails: "Önce anlaşılır bir başlık ve il girin.", draftSaved: "Seçilen fotoğraflar ve konum dahil taslağınız bu cihaza kaydedildi. İlanı tamamlamak için platformda giriş yapın.", draftRestored: "Kaydedilen taslağınız bu cihazda geri yüklendi.", draftOpenNotice: "Taslağınız uygulamada kaydedilmeye devam eder. Giriş yaptıktan sonra güvenli ilan sayfasında alanları tamamlayın ve fotoğrafları yükleyin.", browserCancelledDraft: "İlan tamamlanmadan tarayıcı kapatıldı. Taslağınız kayıtlı kaldı; yeniden deneyebilirsiniz.", browserOpenedPublish: "Güvenli ilan sayfası açıldı. Giriş yapın, sonra ilan bilgilerini girip fotoğrafları yükleyin.", browserFailedPublish: "İlan sayfası açılamadı. Bağlantınızı kontrol edip yeniden deneyin; taslağınız kaydedildi.", imagePermission: "İlana görsel eklemek için fotoğraflara erişim izni verin.", imagesPicked: "{count} fotoğraf seçildi. Bu cihazda tutmak için taslağı kaydedin.", locationPermission: "Konum izni verilmedi; şimdilik konum belirtmeden devam edebilirsiniz.", locationSaved: "Yaklaşık konum seçildi: {latitude}, {longitude}. Saklamak için taslağı kaydedin.", locationRestored: "Konum geri yüklendi: {latitude}, {longitude}.",
    myListingsTitle: "İlanlarım", manageTitle: "İlanlarınızı tek yerden yönetin", manageDetail: "Giriş yaptıktan sonra ilanlarınız düzenleme, duraklatma veya silme seçenekleriyle görünür.", myListingsStatus: "İlanlarım durumu", myListingsStatusDetail: "Bu veriler giriş gerektirir. Bu entegrasyon aşamasında hesap oturumunu uygulamada tutmamak için sayfa güvenli tarayıcıda açılır.", openMyListings: "İlanlarımı aç", openingMyListings: "Güvenli ilanlar sayfanız açılıyor…", browserCancelled: "İşlem tamamlanmadan tarayıcı kapatıldı. Yeniden deneyebilirsiniz.", browserOpenedMyListings: "İlanlar sayfanız güvenli tarayıcıda açıldı. İlanlarınızı yönetmek için giriş yapın.", browserFailedMyListings: "İlanlar sayfanız açılamadı. Bağlantınızı kontrol edip yeniden deneyin.", accountTitle: "Hesabım", signInTitle: "Devam etmek için giriş yapın", signInDetail: "İlanlarınıza, bildirimlerinize ve iletişim bilgilerinize erişmek için hesabınızı kullanın.", openMessages: "Mesajları aç ve giriş yap", openNotifications: "Bildirimleri aç", openingMessages: "Mesajlar açılıyor…", openingNotifications: "Bildirimler açılıyor…", browserOpenedProtected: "{label} güvenli tarayıcıda açıldı. Hesap verilerinize erişmek için giriş yapın.", browserFailedProtected: "{label} açılamadı. Bağlantınızı kontrol edip yeniden deneyin.", chatTitle: "İlan sahibiyle sohbet", chatDetail: "İlan sayfasından veya mesajlardan ilan sahibiyle özel ve güvenli bir sohbet başlatabilirsiniz.", notificationsTitle: "Bildirimler", notificationsDetail: "İlan durumu güncellemeleri ve kullanıcı ilgileri giriş yaptıktan sonra burada görünür.",
  },
};

export function translate(locale: MobileLocale, key: string, values?: TranslationValues) {
  const value = words[locale][key] ?? words.ar[key] ?? key;
  return values ? value.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`)) : value;
}

export async function loadLocale() {
  const stored = await AsyncStorage.getItem("souqna-mobile-locale");
  return stored === "en" || stored === "tr" || stored === "ar" ? stored : "ar";
}

export async function saveLocale(locale: MobileLocale) {
  await AsyncStorage.setItem("souqna-mobile-locale", locale);
}
